Repository danielSanchezQ/rusty_results, pull requests merged in 2022-05, with the labels that each got.

#9 Implement Option.flatten and Option.flatten_one methods.
  rusty_results/prelude.py
  rusty_results/tests/option/test_option_empty.py
  rusty_results/tests/option/test_option_some.py
Labels: documentation, enhancement

#11 Added python 3.10 to ci test matrix
  .github/workflows/ci.yml
  requirements_dev.txt
Labels: CI

#12 Result flatten and transpose implementations
  rusty_results/prelude.py
  rusty_results/tests/option/test_option_empty.py
  rusty_results/tests/option/test_option_some.py
  rusty_results/tests/result/test_result_err.py
  rusty_results/tests/result/test_result_ok.py
Labels: enhancement
